### ISSUE TITLE
Stemless keys have incorrect overlapping model

### ISSUE THREAD

**Issue by schapmangt** [rsheldiii/KeyV2#63] opened 2020-09-22 03:12 UTC
**What version of OpenSCAD are you on?**
 2019.05

**Describe the bug**
When rendering a key without a stem, a second, larger key model overlaps the key we want to render.

**To Reproduce**
Render the following code:

use <src/key.scad>
include <src/settings.scad>
include <src/key_sizes.scad>
include <src/key_profiles.scad>
include <src/key_types.scad>
include <src/key_transformations.scad>
$stem_type="disable";
key();

**Additional context**
Removing or commenting out $stem_type="disable"; fixes the rendering.  [Screenshot here](https://www.dropbox.com/s/dj912veaqxfrnm2/stemless.png?dl=0)

**Comment by schapmangt** [comment] 2020-09-22 03:17
Workaround: Specify a valid stem type and set its depth variable to zero. 

This will produce a stemless key without this issue:

$stem_type="rounded_cherry";
$rounded_cherry_stem_d=0;
key();

**Comment by mrebersv** [comment] 2021-07-21 14:35
This is totally 10 months after you opened this issue.  I'm not sure if this was fixed in KeyV2 or not, but I can't reproduce now (OpenSCAD version 2021.01).  Glad you found a workaround back then, and it might not be a problem anymore.

**Comment by rsheldiii** [comment] 2022-02-20 00:59
I can no longer repro this on v1, the same code gets me a correctly rendered keycap:

![image](https://user-images.githubusercontent.com/510867/154824299-4dee8a72-bb21-4008-b2b7-e94575179fd2.png)


it's been a while so it may have gotten fixed in another story somewhere. I'm closing this, please reopen if the problem persists

**Closed by rsheldiii** 2022-02-20 00:59 UTC
Labels: fixed-in-v2
