### ISSUE TITLE
[Enhancement/Feature Request] MT3 Profile

### ISSUE THREAD

**Issue by seanmaisch** [rsheldiii/KeyV2#91] opened 2021-03-01 05:43 UTC
I really love this library, it's fantastic! However, my favorite keycap profile is absent!

Here's a write-up by the creator, Matt3o, about the profile.
https://matt3o.com/about-mt3-profile-and-devtty-set/

I'd love to see this in here, and hell, I'd even buy you a set of MT3 @rsheldiii, should you choose to enter this profile into the library. I lack the technical expertise, as well as the calipers and other tools, to make this happen.

Any thoughts on if it's possible?

**Comment by jwhendy** [comment] 2021-04-07 03:59
Seconding. If the issue is measurements/models. I may have a lead on a set to use as a reference.

Is there hesitation around replicating a new/modern set a specific person designed recently vs. most of these keycap designs being fairly ancient? Not sure how that works, but wanted to voice it (and don't know the answer, nor do I want to infringe on anyone's intellectual property/designs or tarnish the keyboard community via something like this).

**Comment by mrebersv** [comment] 2021-07-21 14:08
I made a pull request for my approximation of the "matty3" profile (didn't know if MT3 name is allowed to be used or not in this one).  It hasn't been pulled into the main repo, but you can mess around with it here:

https://github.com/mrebersv/KeyV2

**Comment by jwhendy** [comment] 2021-07-21 16:08
@mrebersv for paranoia's sake, I had been looking at sort of freedom to practice with keycap designs. I'm new to the space and just didn't know the legality of copying, reproducing, etc. It seemed some suggested that older, retro styles were sort of fair game, but perhaps not as much for new models with a degree of propriety.

This is the only [official quasi-statement](https://matt3o.com/mt3-stl-files-for-artisan-keycap-designers/) I've seen:

> Well wait no more, STL for ROW 0 and 6.25u spacebar are here! Use them freely even for commercial products but please give credit. The license is Attribution-ShareAlike just let your customers know your work is based on MT3 profile designed by me and we are good :)

So, perhaps simply stating that it's derived from MT3 is sufficient when one reproduces, even for sale? Just figured it was worth bringing up. I don't think I've seen anything like licensing, patenting, or similar for *any* keycap yet, so again, this could easily just be paranoia. I've thought about making these for sale, so just wanted to think out loud and it's applicable to pulling in here.

**Comment by mrebersv** [comment] 2021-07-21 17:16
Good find!  I'm really not sure about the legality here.  I don't think it would be illegal to "clean room" reverse engineer it by taking measurements, etc.  Selling reproductions based on that is likely more of a gray area, though the link to that license is interesting.  Frankly, MT3 was effectively copying IBM's Beamspring keycaps, then were modified slightly.  It seems to me that if "matty3," spritually based off of MT3 (though undoubtedly not identical since there was plenty of guessing), were to be an infringement of MT3, then MT3 would be an infringement on IBM's work.  

I do have a set of mt3 keycaps coming in the next week, so I will be able to take measurements to see how close I was.  Some of the dimensions were taken by a person in Germany who took some measurements for me when I asked, but they weren't too precise.  I won't have a 3d printer until late October (I pre-ordered a Phrozen Mega 8k that ships around then) though, so I still will only be able to compare MT3 keys to the models rendered in OpenSCAD.  

FWIW, I think I pretty much nailed the scoop, aside from the depth, but that can be updated.  There's also a "deep dish" option for the homing keys (F and J on a QWERTY).  I'm pretty positive how that option is invoked is not how it should be, but I don't really know enough OpenSCAD or how this project should be structured to fix it yet.  There's a slight dip on the corners with deep dish on.  I don't think it would affect the feel at all since you wouldn't be touching the key at that spot ever.  You'll need to use my fork (https://github.com/mrebersv/KeyV2) until the pull request is accepted in the main repo.  Here's a sample `keys.scad` to see it for all rows:

```
include <./includes.scad>
for (x = [0:1:5]) {
  translate_u(0,-x) matty3_row(x) key();
  translate_u(1,-x) matty3_row(x, $deep_dish=true) key();
} 
```
I'll try to figure out the license requirements you linked and get them incorporated to the code comments.

Let me know what you think!

**Comment by mrebersv** [comment] 2021-07-21 17:18
@seanmaisch Let me know if you're still offering up a sample MT3 set 😉 

I actually have an ortho set on the way to use.

**Comment by mrebersv** [comment] 2021-07-21 17:47
@jwhendy Actually, I don't think I committed my deep dish changes yet, probably because of that corner bug.

**Comment by jwhendy** [comment] 2021-07-21 18:07
@mrebersv great comments, and I didn't know it was derived/based on the beam spring keys. I'm an engineer, and at best this would be a design patent, covering the look, which seems tough in a dense space like this with such similarity between all available keycaps. There would have to be some key (ha, unintended pun) geometry to definitively identify this as MT3 vs. something else, and that might only be possible for certain rows and not others, where the similarities are much greater to another set.

Plus, building on your point, one would have to show this design wasn't disclosed in the past, including prototypes, as long as they publicly have been posted somewhere, or even illustrated as a mockup. As I work in manufacturing, I think the general barrier to rip-off is the capital investment on the molds, minimum quantities to make a run, and being the first to release/distribute/brand it.

Still, I would respect the author's wishes. Anyone could do what you're doing so again this was more about thinking out loud. I feel good that at least should matt3o stumble on this, we've not hidden this and he'd be free to clarify his stance and in what use cases/quantities this would be considered a party foul.

P.S. I actually splurged on a used camillo set a few months ago. It was a full set and my build was just a 60%. I have tons of keys I'll never use. Let me know if this would be helpful to you. I have nice calipers if you want legit measurements, and I've also considered setting pieces up to shoot profile pics with my dslr. Spline tracing a silhouette from side/front came to mind as another way to digitize the shape :) jw [dot] hendy [at] gmail if you'd like to talk offline!

**Comment by mrebersv** [comment] 2021-07-21 18:20
Oh legit measurements would be fantastic.  I bet your calipers are nicer than mine, which were apparently way nicer than the German who helped initially.  These were the measurements I asked for from him/her (copy/paste from a message I sent):

1. Width at the base/bottom of the keycap
2. Length at the base/bottom of the keycap
3. Width at the top of the keycap
4. Length at the top of the keycap
5. Height at a front corner
6. Height at the front center
7. Height at a back corner
8. Height at the sides' centers
9. Depth of the dish at the center of the keycap (you may need to lay something on top of the keycap connecting the centers on the left and right side, then use the pointy end of the caliper to get the depth)

These nine measurements essentially get us all we need.   Arctangent got me the angles I used from his measurements.  If you are willing to redo the measurements with your calipers and keys, millimeters (hopefully, to the 0.01) please.  If not, no worries.  I'll have a set soon enough and my calipers will be more than fine.

**Comment by jwhendy** [comment] 2021-07-21 18:50
@mrebersv Got your email and replied there before seeing this. I can probably do this in a night :) Any advantage to just doing the silhouette method? I can do calipers, but having silhouettes with a single easy-to-measure reference to convert px to mm enables measuring any other key point.

Maybe I'll start with calipers, along with a generic pic for reference to make a quasi-drawing, and can post these for each row by, say, end of the weekend. Thanks for the list as I have not dug into what openscad needs. I figured you could do it as well, but wondered if ortho would be all R3?

**Comment by rsheldiii** [comment] 2022-02-22 15:28
closed with https://github.com/rsheldiii/KeyV2/pull/149!

**Closed by rsheldiii** 2022-02-22 15:28 UTC
Labels: enhancement
