### ISSUE TITLE
Function parameters inconsistent: $stem_inner_slop vs $stem_slop vs slop

### ISSUE THREAD

**Issue by XScorpion2** [rsheldiii/KeyV2#72] opened 2020-11-18 21:31 UTC
**What version of OpenSCAD are you on?**
Master branch

**Describe the bug**
OpenSCAD Configurator uses $stem_inner_slop, and the code inside of upside_down(...) checks for $stem_inner_slop, however the stem code itself uses $stem_slop

**To Reproduce**
Pull master and open the keys.scad
Use this snippet for rendering a key:

```
sa_row(5)
u(1.25)
inset(val=1)
rounded_cherry($stem_slop=0)
inverted()
upside_down($stem_inner_slop=0)
key();
```

Replace `rounded_cherry($stem_slop=0)` with `rounded_cherry(0)` or `rounded_cherry(slop=0)` and notice the stem reverts to the default 0.2 slop.
Replace `upside_down($stem_inner_slop=0)` with `upside_down()` and click render, notice the Echo error about stem slop should be 0 for upside down printing.

**Additional context**

**Comment by rsheldiii** [comment] 2022-02-19 20:41
looks like this is caused by the arguments in the helper functions, they should be like so:

```
module cherry(slop = undef) {
  $stem_slop = slop != undef ? slop : $stem_slop;
  $stem_type = "cherry";
  children();
}
```

the second issue is just a recommendation, so it isn't a bug. You can set `$stem_inner_slop` to 0 anywhere in the method tree.

**Comment by rsheldiii** [comment] 2022-02-20 01:05
fixed in V1 as well. thanks for finding this!

**Closed by rsheldiii** 2022-02-20 01:05 UTC
Labels: fixed-in-v2
